FROM  golang:1.20

#ENV GOPROXY=direct
COPY . /go/src/github.com/monmohan/docker-log-driver
RUN cd /go/src/github.com/monmohan/docker-log-driver && go build --ldflags '-extldflags "-static"' -o /usr/bin/docker-log-driver
